src/Domain/Entity/Product/Product.php
<?php

namespace App\Domain\Entity\Product;

use App\Domain\Entity\AbstractEntity;
use App\Domain\Entity\Commerce\Brand;
use App\Domain\Entity\CreationDateTrait;
use App\Domain\Entity\IsVisibleTrait;
use App\Domain\Entity\LocaleTrait;
use App\Domain\Entity\MetaTrait;
use App\Domain\Entity\OrderIndexTrait;
use App\Domain\Entity\SlugTrait;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @author Anton Zakharuk <anton.zakharuk@cosmonova.net>
 *
 * @ORM\Entity()
 * @UniqueEntity(fields={"slug"})
 */
class Product extends AbstractEntity
{
    public const MARKING_NONE = 'none';
    public const MARKING_NEW = 'new';
    public const MARKING_TOP = 'top';
    public const MARKING_SALE = 'sale';
    public const MARKING_SOON = 'soon';
    public const MARKING_PRE_ORDER = 'pre_order';

    use LocaleTrait;
    use CreationDateTrait;
    use MetaTrait;
    use SlugTrait;
    use IsVisibleTrait;
    use TranslatableProductFields;
    use OrderIndexTrait;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private ?float $price = null;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private ?float $salePrice = null;

    /**
     * @ORM\Column(type="string", nullable=false, options={"default": "none"})
     */
    private string $marking;

    /**
     * @ORM\OneToMany(targetEntity="App\Domain\Entity\Product\ProductTranslation", mappedBy="product", cascade={"all"})
     */
    private Collection $translations;

    /**
     * @ORM\OneToMany(targetEntity="App\Domain\Entity\Product\ProductImage", mappedBy="product", cascade={"all"})
     */
    private Collection $images;

    /**
     * @ORM\OneToMany(targetEntity="App\Domain\Entity\Product\ProductSpecification", mappedBy="product", cascade={"all"})
     */
    private Collection $specifications;

    /**
     * @ORM\ManyToMany(targetEntity="App\Domain\Entity\Product\ProductCategory", inversedBy="products")
     */
    private Collection $categories;

    /**
     * @ORM\OneToMany(targetEntity="App\Domain\Entity\Product\ProductComment", mappedBy="product", cascade="all")
     */
    private Collection $comments;

    /**
     * @ORM\ManyToOne(targetEntity="App\Domain\Entity\Commerce\Brand", inversedBy="products")
     * @ORM\JoinColumn(onDelete="SET NULL")
     */
    private ?Brand $brand = null;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private ?string $vendorCode = null;

    public function __construct()
    {
        $this->translations = new ArrayCollection();
        $this->images = new ArrayCollection();
        $this->specifications = new ArrayCollection();
        $this->creationDate = new \DateTimeImmutable();
        $this->marking = self::MARKING_NONE;
        $this->comments = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): void
    {
        $this->price = $price;
    }

    public function getSalePrice(): ?float
    {
        return $this->salePrice;
    }

    public function setSalePrice(float $salePrice): void
    {
        $this->salePrice = $salePrice;
    }

    public function getMarking(): string
    {
        return $this->marking;
    }

    public function setMarking(string $marking): void
    {
        $this->marking = $marking;
    }

    /**
     * @return ProductTranslation[]|Collection
     */
    public function getTranslations(): Collection
    {
        return $this->translations;
    }

    /**
     * @return Collection|ProductImage[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function getPreviewImage(): ?ProductImage
    {
        $images = array_filter($this->getImages()->toArray(), function ($image) {
            return $image->isPreview();
        });

        return count($images) > 0 ? current($images) : null;
    }

    /**
     * @return ProductSpecification[]|Collection
     */
    public function getSpecifications()
    {
        return $this->specifications;
    }

    /**
     * @return ProductCategory[]|Collection
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(ProductCategory $productCategory): void
    {
        if (!$this->categories->contains($productCategory)) {
            $this->categories->add($productCategory);
        }
    }

    public function getComments()
    {
        return $this->comments;
    }

    public function isOnSale(): bool
    {
        return $this->marking === self::MARKING_SALE;
    }

    public function getBrand(): ?Brand
    {
        return $this->brand;
    }

    public function setBrand(?Brand $brand): void
    {
        $this->brand = $brand;
    }

    public function getVendorCode(): ?string
    {
        return $this->vendorCode;
    }

    public function setVendorCode(?string $vendorCode): void
    {
        $this->vendorCode = $vendorCode;
    }
}

src/Http/Controller/Site/CheckoutController.php
<?php

namespace App\Http\Controller\Site;

use App\Domain\Entity\Commerce\Order;
use App\Domain\Entity\Site\Page;
use App\Domain\Entity\User\Admin;
use App\Domain\Repository\OrderRepository;
use App\Domain\Repository\PageRepository;
use App\Http\Response\Forms\Types\Order\UserOrderType;
use App\Infrastructure\ExternalService\NovaPoshtaClient;
use App\Infrastructure\Locales;
use App\Infrastructure\Mailer\Email\AdminOrderCreatedEmail;
use App\Infrastructure\Mailer\SimpleMailer;
use App\Infrastructure\Service\Cart\SessionCart;
use App\Infrastructure\Service\EntityTranslator;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @author Anton Zakharuk <anton.zakharuk@cosmonova.net>
 *
 * @Route("/{_locale}/checkout", name="site_checkout_")
 */
class CheckoutController extends AbstractSiteController
{
    /**
     * @Route("", name="index")
     */
    public function index(
        Request $request,
        SessionCart $sessionCart,
        NovaPoshtaClient $novaPoshtaClient,
        PageRepository $pageRepository,
        SessionInterface $session,
        SimpleMailer $mailer
    ) {
        $translator = new EntityTranslator($request->getLocale());
        $page = $pageRepository->findOneBy(['staticType' => Page::STATIC_TYPE_CHECKOUT]);

        $cart = $sessionCart->get();
        if ($cart->isEmpty()) {
            return $this->redirectToRoute('site_cart_index');
        }

        $form = $this->createForm(UserOrderType::class, new Order());
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Order $order */
            $order = $form->getData();
            $order->setOrderNumber(bin2hex(random_bytes(3)));
            $order->setCart($sessionCart->getProductBag());
            $order->setUser($this->getUser() instanceof Admin ? null : $this->getUser());

            if ($order->getDeliveryType() === Order::DELIVERY_TYPE_NOVA_POSHTA_WAREHOUSE) {
                $novaCity = current($novaPoshtaClient->getCityByRef($order->getNovaPoshtaCity()));

                $novaCityName = $novaCity['Description'];
                if ($request->getLocale() === Locales::RU) {
                    $novaCity['DescriptionRu'];
                }

                $order->setNovaPoshtaCity($novaCityName);
            }

            $this->getDoctrine()->getManager()->persist($order);
            $this->getDoctrine()->getManager()->flush();

            $sessionCart->clear();
            $session->set('order', $order->getId());

            $email = new AdminOrderCreatedEmail($order);
            $mailer->send($email);

            return $this->redirectToRoute('site_checkout_order_created');
        }

        return $this->renderTemplate(
            'site/pages/checkout/index.html.twig',
            [
                'cart' => $cart,
                'form' => $form->createView(),
                'meta' => $translator->trans($page)
            ]
        );
    }

    /**
     * @Route("/order-created", name="order_created")
     */
    public function orderCreated(
        Request $request,
        PageRepository $pageRepository,
        OrderRepository $orderRepository,
        SessionInterface $session
    ) {
        $translator = new EntityTranslator($request->getLocale());

        /** @var Order $order */
        $order = $orderRepository->find($session->get('order', 0));
        if (null === $order) {
            throw new NotFoundHttpException();
        }

        $page = $order->isOnlinePayment() ? Page::STATIC_TYPE_CHECKOUT_ONLINE_ORDER_THANK_YOU : Page::STATIC_TYPE_CHECKOUT_THANK_YOU;
        $page = $pageRepository->findOneBy(['staticType' => $page]);

        return $this->renderTemplate(
            'site/pages/checkout/thank_you.html.twig',
            [
                'page' => $translator->trans($page),
                'order' => $order
            ]
        );
    }

    /**
     * @Route("/nova/cities/{cityRef}/warehouses", name="get_nova_warehouses", methods={"GET"})
     */
    public function getNovaWarehouses(string $cityRef, NovaPoshtaClient $novaPoshtaClient)
    {
        return $this->json($novaPoshtaClient->getWarehouses($cityRef));
    }
}

templates/site/pages/checkout/index.html.twig
{% extends 'site/layout.html.twig' %}

{% block pageTitle %}{{ meta.pageTitle }}{% endblock %}
{% block metaTitle %}{{ meta.metaTitle }}{% endblock %}
{% block metaDescription %}{{ meta.metaDescription }}{% endblock %}
{% block metaKeywords %}{{ meta.metaKeywords }}{% endblock %}

{% block javascripts %}
    {{ parent() }}

    {{ encore_entry_script_tags('site-checkout') }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}

    {{ encore_entry_link_tags('site-checkout') }}
{% endblock %}

{% block content %}
    <div class="container-fluid mt-3 mb-5">
        <div class="row justify-content-center">
            <div class="col-xl-6 col-lg-7 col-md-12 col-12">
                <div class="card shadow">
                    <div class="card-body">
                        {{ form_start(form) }}
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.name) }}
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.surname) }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.phone) }}
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.email) }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.paymentType) }}
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.deliveryType) }}
                                </div>
                            </div>
                        </div>
                        <div class="row" id="courier-delivery-fields">
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.deliveryCity) }}
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.deliveryAddress) }}
                                </div>
                            </div>
                        </div>
                        <div class="row" id="nova-poshta-delivery-fields">
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.novaPoshtaCity) }}
                                </div>
                            </div>
                            <div class="col-md-6 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.novaPoshtaWarehouse) }}
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12 col-12">
                                <div class="mb-3">
                                    {{ form_row(form.comment) }}
                                </div>
                            </div>
                        </div>
                        <div class="row justify-content-end">
                            <div class="col-xl-4 col-lg-6 col-12 text-end">
                                <div class="mb-3">
                                    {{ form_row(form.save) }}
                                </div>
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
            <div class="col-xl-4 col-lg-5 col-md-12 col-12 cart-container">
                <div class="card shadow">
                    <div class="card-body">
                        {% for cartProduct in cart.products %}
                            {% set product = transEntity(cartProduct.product) %}
                        <div class="row mb-3">
                            <div class="col-xl-2 col-lg-2 col-2">
                                <img class="img-fluid" src="{{ asset(product.previewImage ? product.previewImage.file ? product.previewImage.file.relativePath : '' : '') }}">
                            </div>
                            <div class="col-xl-5 col-lg-5 col-5">
                                {{ sliceString(product.name) }}
                            </div>
                            <div class="col-xl-5 col-lg-5 col-5">
                                <div class="container-fluid">
                                    <div class="row">
                                        {% for productSpecificationValue in cartProduct.specificationValues %}
                                            {% set relatedValue = transEntity(productSpecificationValue.relatedSpecificationValue) %}
                                            {% set relatedSpecification = transEntity(productSpecificationValue.relatedSpecificationValue.specification) %}
                                            <div class="col-xl-12 col-lg-12 col-12">
                                                {{ relatedSpecification.name }}: {{ relatedValue.name }}
                                            </div>
                                        {% endfor %}
                                        <div class="col-xl-12 col-lg-12 col-12">
                                            {{ 'Qty'|trans }}: {{ cartProduct.quantity }}
                                        </div>
                                        <div class="col-xl-12 col-lg-12 col-12">
                                            {{ 'Price'|trans }}: {{ cartProduct.totalPrice }} {{ 'uah.'|trans }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="row justify-content-end mt-3 text-end">
                            <div class="col-lg-6 col-12">
                                <div class="sub-title">
                                    {{ 'Total price'|trans }}: {{ cart.totalPrice}} {{ 'uah.'|trans }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/site/pages/checkout/thank_you.html.twig
{% extends 'site/layout.html.twig' %}

{% block pageTitle %}{{ page.pageTitle }}{% endblock %}
{% block metaTitle %}{{ page.metaTitle }}{% endblock %}
{% block metaDescription %}{{ page.metaDescription }}{% endblock %}
{% block metaKeywords %}{{ page.metaKeywords }}{% endblock %}

{% block content %}
    <div class="container mt-3 mb-5">
        <div class="row justify-content-center text-center">
            <div class="col-12">
{#                <div class="card shadow-lg">#}
{#                    <div class="card-body">#}
                        <div class="alert alert-warning">
                            {{ page.content|raw }}
                        </div>
{#                    </div>#}
{#                </div>#}
            </div>
            <div class="col-12">
                <div class="card shadow-lg mt-2">
                    <div class="card-header title">
                        {{ 'Your order'|trans }} #{{ order.orderNumber }}
                    </div>
                    <div class="card-body">
                        {% set cart = orderCart(order) %}
                        {% for cartProduct in cart.products %}
                            <div class="row">
                                {% set product = transEntity(cartProduct.product) %}
                                <div class="col-xl-1 col-lg-1 col-1">
                                    <img class="img-fluid"
                                         src="{{ asset(product.previewImage ? product.previewImage.file ? product.previewImage.file.relativePath : '' : '') }}">
                                </div>
                                <div class="col-xl-6 col-lg-6 col-5">
                                    {{ product.name }}
                                </div>
                                <div class="col-xl-4 col-lg-4 col-5">
                                    <div class="container-fluid">
                                        <div class="row">
                                            {% for productSpecificationValue in cartProduct.specificationValues %}
                                                {% set relatedValue = transEntity(productSpecificationValue.relatedSpecificationValue) %}
                                                {% set relatedSpecification = transEntity(productSpecificationValue.relatedSpecificationValue.specification) %}
                                                <div class="col-xl-12 col-lg-12 col-12">
                                                    {{ relatedSpecification.name }}: {{ relatedValue.name }}
                                                </div>
                                            {% endfor %}
                                            <div class="col-xl-12 col-lg-12 col-12">
                                                {{ 'Qty'|trans }}: {{ cartProduct.quantity }}
                                            </div>
                                            <div class="col-xl-12 col-lg-12 col-12">
                                                {{ 'Price'|trans }}: {{ cartProduct.totalPrice }} {{ 'uah.'|trans }}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="row justify-content-end mt-1 text-end">
                            <div class="col-lg-6 col-12">
                                <div class="sub-title">
                                    {{ 'Total price'|trans }}: {{ cart.totalPrice }} {{ 'uah.'|trans }}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}